# Generated by Django 6.0.5 on 2026-08-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_notes_booking_purpose_and_more'),
        ('rental', '0004_implement'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='selected_implements',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='rental.implement'),
        ),
    ]
