# Generated by Django 6.0.5 on 2026-08-12 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_selected_implements'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_type',
            field=models.CharField(choices=[('owner_delivers', 'Owner Delivers Tractor to My Farm'), ('customer_pickup', 'Self Pickup from Owner Yard')], default='owner_delivers', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='estimated_distance_km',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_farm_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Request Sent'), ('approved', 'Owner Accepted'), ('arrived', 'Arrived on Site'), ('in_progress', 'Work In Progress'), ('paid', 'Payment Done'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
