# Generated by Django 6.0.5 on 2026-08-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_delivery_type_booking_estimated_distance_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completion_otp',
            field=models.CharField(blank=True, default='4892', max_length=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_meter_hours',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_meter_hours',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=8, null=True),
        ),
    ]
