# Generated by Django 6.0.5 on 2026-08-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_completion_otp_booking_end_meter_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='rental_units',
        ),
        migrations.AddField(
            model_name='booking',
            name='crop_name',
            field=models.CharField(blank=True, default='Cotton (કપાસ)', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='farming_work_type',
            field=models.CharField(blank=True, choices=[('plowing', '🌾 Land Plowing / Tillage (જમીન ખેડવા / ખેડાણ)'), ('transport', '🚛 Crop Transport / Trolley Haulage (પાક માલવહન / ટ્રોલી)'), ('rotavator', '🔄 Fine Soil Bed Prep (રોટાવેટર / માટી ભભરાવવી)'), ('sowing', '🌱 Sowing / Seeding (વાવણી / ઓરણી)'), ('harvesting', '🚜 Threshing / Harvesting (કાપણી / થ્રેશર)'), ('leveling', '📐 Land Leveling (જમીન સમથળ / લેવલિંગ)'), ('spraying', '💧 Pesticide Spraying (દવા છંટકાવ)'), ('general', '⚙️ General Agricultural Work (સામાન્ય ખેતીકામ)')], default='plowing', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='land_area_size',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='booking',
            name='land_area_unit',
            field=models.CharField(default='bigha', max_length=20),
        ),
    ]
