# Generated by Django 6.0.5 on 2026-08-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_booking_rental_units_booking_crop_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rental_units',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
