# Generated by Django 6.0.5 on 2026-08-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tractors/'),
        ),
    ]
