# Generated by Django 6.0.5 on 2026-08-11 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_tractor_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tractor',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='tractor',
            name='city_village',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tractor',
            name='district',
            field=models.CharField(default='Ahmedabad', max_length=100),
        ),
        migrations.AddField(
            model_name='tractor',
            name='fuel_type',
            field=models.CharField(choices=[('diesel', 'Diesel'), ('petrol', 'Petrol'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='diesel', max_length=20),
        ),
        migrations.AddField(
            model_name='tractor',
            name='is_approved_by_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tractor',
            name='manufacturing_year',
            field=models.PositiveIntegerField(default=2022),
        ),
        migrations.AddField(
            model_name='tractor',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='tractor',
            name='rent_per_hour',
            field=models.DecimalField(decimal_places=2, default=250.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tractor',
            name='state',
            field=models.CharField(default='Gujarat', max_length=100),
        ),
        migrations.AddField(
            model_name='tractor',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tractor',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('hydrostatic', 'Hydrostatic')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='tractor',
            name='horsepower',
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.CreateModel(
            name='TractorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tractors/gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='rental.tractor')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
                ('tractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='rental.tractor')),
            ],
            options={
                'unique_together': {('customer', 'tractor')},
            },
        ),
    ]
