# Generated by Django 6.0.5 on 2026-08-11 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_tractor_avg_rating_tractor_city_village_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Implement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('rotavator', 'Rotavator'), ('cultivator', 'Cultivator / Plought'), ('trailer', 'Trailer / Trolley'), ('harvester', 'Combine Harvester / Thresher'), ('seeder', 'Seed Drill / Seeder'), ('leveler', 'Laser Land Leveler'), ('other', 'Other Equipment')], default='rotavator', max_length=50)),
                ('rent_per_hour', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('rent_per_day', models.DecimalField(decimal_places=2, default=600.0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='implements/')),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implements', to=settings.AUTH_USER_MODEL)),
                ('tractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attached_implements', to='rental.tractor')),
            ],
        ),
    ]
