# Generated by Django 6.0.5 on 2026-08-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_implement'),
    ]

    operations = [
        migrations.AddField(
            model_name='tractor',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=22.9868, max_digits=9),
        ),
        migrations.AddField(
            model_name='tractor',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=72.3787, max_digits=9),
        ),
    ]
